version: '3.7'
services:
# -------------------------------------------------------------------------------------------
  redis-master:
    hostname: redis-master
    container_name: redis-master
    image: redis:latest
    # 容器启动命令
    command: [ "redis-server", "/data/conf/redis-master.conf" ]
    ports:
      - 6379:6379
    working_dir: /data # 工作目录
    networks:
      - net-portrait
    env_file:
      - ./env/common.env
    volumes:
      # 配置文件挂载
      - ./conf/redis-master.conf:/data/conf/redis-master.conf
      - ./conf/redis.conf:/data/conf/redis.conf
      # 数据和日志挂载
      - ./data/master/:/data
    restart: always
# -------------------------------------------------------------------------------------------
  # redis从节点
  redis-slave1:
    hostname: redis-slave1
    container_name: redis-slave1
    image: redis:latest
    # 容器启动命令
    command: [ "redis-server", "/data/conf/redis-slave.conf" ]
    ports:
      - 6380:6379
    working_dir: /data # 工作目录
    networks:
      - net-portrait
    env_file:
      - ./env/common.env
    volumes:
      # 配置文件
      - ./conf/redis.conf:/data/conf/redis.conf
      - ./conf/redis-slave.conf:/data/conf/redis-slave.conf
      # 数据
      - ./data/slave1/:/data
    depends_on:
      - redis-master
    restart: always
# -------------------------------------------------------------------------------------------
  # redis从节点
  redis-slave2:
    hostname: redis-slave2
    container_name: redis-slave2
    image: redis:latest
    # 容器启动命令
    command: [ "redis-server", "/data/conf/redis-slave.conf" ]
    ports:
      - 6381:6379
    working_dir: /data # 工作目录
    networks:
      - net-portrait
    env_file:
      - ./env/common.env
    volumes:
      # 配置文件
      - ./conf/redis.conf:/data/conf/redis.conf
      - ./conf/redis-slave.conf:/data/conf/redis-slave.conf
      # 数据
      - ./data/slave2/:/data
    depends_on:
      - redis-master
    restart: always
# -------------------------------------------------------------------------------------------
# 网络
networks:
  net-portrait:
    external:
      name: net-portrait